services:
  api:
    build:
      context: .
      target: api
    image: systematic-trading-data-warehouse-api
    platform: linux/amd64
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  # cron:
  #   build:
  #     context: .
  #     target: cron
  #   image: systematic-trading-data-warehouse-cron
  #   platform: linux/amd64
  #   env_file: .env
  #   # Cron expressions in docker/crontab are interpreted in this timezone.
  #   environment:
  #     TZ: UTC
  #   restart: unless-stopped
